sap.ui.define([
    "sap/ui/model/json/JSONModel",
    "sap/ui/Device"
], function (JSONModel, Device) {
    "use strict";
    return {
        createDeviceModel: function () {
            var oModel = new JSONModel(Device);
            oModel.setDefaultBindingMode("OneWay");
            return oModel;
        },
        createSchemeModel: function () {
            var aScheme = [
                {
                    idscheda: "00000001",
                    stato: "B",
                    idsc_mdl: "",
                    ernam: "USER001",
                    erdat: "20260901",
                    erzet: "120000",
                    aenam: "",
                    aedat: "",
                    aezet: "",
                    dtcomp: "20260901",
                    idbene: "BENE001",
                    entepr: "Regione Lombardia",
                    txbene: "Palazzo Amministrativo Centro",
                    coogis: "45.4642,9.1895",
                    fabter: "01",
                    usofab: "01",
                    usoter: "",
                    suplut: "15000",
                    supfon: "20000",
                    access: "01",
                    porzed: "01",
                    numedi: "1",
                    numfuo: "5",
                    nument: "1",
                    colleg: "01",
                    stport: "01",
                    tampon: "01",
                    copert: "01",
                    serram: "01",
                    partiz: "01",
                    finitu: "01",
                    impian: "01",
                    pertin: "01",
                    supcop: "12000",
                    supsco: "8000",
                    zonomi: "MI01",
                    ape: "SI",
                    clsene: "A1",
                    titolo: "01",
                    annopr: "1990",
                    limiti: "00",
                    annocs: "1985",
                    stgene: "01",
                    stspor: "01",
                    stcope: "01",
                    sttamp: "01",
                    stches: "01",
                    stpart: "01",
                    stfini: "01",
                    stimpi: "01",
                    stnote: "01",
                    stoccu: "01",
                    sogocc: "Comune Milano",
                    natocc: "01",
                    tipocc: "01",
                    vincol: "00",
                    intcul: "00",
                    autali: "00",
                    dsturb: "01",
                    iterur: "00",
                    titori: "SI",
                    ante67: "SI",
                    ante42: "SI",
                    corcat: "SI",
                    ceragi: "01",
                    collst: "01",
                    docamb: "01",
                    vulssm: "00",
                    vulamb: "00",
                    stimav: "5000000",
                    stimnt: "Valutazione di mercato",
                    annovl: "2026",
                    canloc: "25000",
                    prgprc: "00",
                    delibe: "01",
                    espgar: "01",
                    esitoa: "00"
                },
                {
                    idscheda: "00000002",
                    stato: "D",
                    idsc_mdl: "",
                    ernam: "USER002",
                    erdat: "20260815",
                    erzet: "140000",
                    aenam: "USER001",
                    aedat: "20260901",
                    aezet: "150000",
                    dtcomp: "20260815",
                    idbene: "BENE002",
                    entepr: "Regione Lombardia",
                    txbene: "Edificio Uffici Settore Patrimonio",
                    coogis: "45.4650,9.1900",
                    fabter: "01",
                    usofab: "02",
                    usoter: "",
                    suplut: "8500",
                    supfon: "12000",
                    access: "00",
                    porzed: "01",
                    numedi: "1",
                    numfuo: "4",
                    nument: "0",
                    colleg: "01",
                    stport: "01",
                    tampon: "02",
                    copert: "01",
                    serram: "02",
                    partiz: "01",
                    finitu: "02",
                    impian: "02",
                    pertin: "00",
                    supcop: "7000",
                    supsco: "5000",
                    zonomi: "MI02",
                    ape: "SI",
                    clsene: "B",
                    titolo: "01",
                    annopr: "1995",
                    limiti: "00",
                    annocs: "1990",
                    stgene: "02",
                    stspor: "01",
                    stcope: "02",
                    sttamp: "02",
                    stches: "02",
                    stpart: "01",
                    stfini: "02",
                    stimpi: "02",
                    stnote: "02",
                    stoccu: "00",
                    sogocc: "",
                    natocc: "00",
                    tipocc: "00",
                    vincol: "01",
                    intcul: "01",
                    autali: "00",
                    dsturb: "02",
                    iterur: "01",
                    titori: "SI",
                    ante67: "NO",
                    ante42: "NO",
                    corcat: "SI",
                    ceragi: "02",
                    collst: "00",
                    docamb: "00",
                    vulssm: "01",
                    vulamb: "00",
                    stimav: "3000000",
                    stimnt: "Valutazione conservativa",
                    annovl: "2025",
                    canloc: "15000",
                    prgprc: "01",
                    delibe: "02",
                    espgar: "00",
                    esitoa: "00"
                },
                {
                    idscheda: "00000003",
                    stato: "B",
                    idsc_mdl: "00000001",
                    ernam: "USER003",
                    erdat: "20260905",
                    erzet: "100000",
                    aenam: "",
                    aedat: "",
                    aezet: "",
                    dtcomp: "20260905",
                    idbene: "BENE003",
                    entepr: "Regione Lombardia",
                    txbene: "Terreno Agricolo Centro",
                    coogis: "45.4700,9.2000",
                    fabter: "02",
                    usofab: "",
                    usoter: "01",
                    suplut: "0",
                    supfon: "50000",
                    access: "00",
                    porzed: "00",
                    numedi: "0",
                    numfuo: "0",
                    nument: "0",
                    colleg: "00",
                    stport: "00",
                    tampon: "00",
                    copert: "00",
                    serram: "00",
                    partiz: "00",
                    finitu: "00",
                    impian: "00",
                    pertin: "00",
                    supcop: "0",
                    supsco: "50000",
                    zonomi: "MI03",
                    ape: "NO",
                    clsene: "00",
                    titolo: "02",
                    annopr: "2000",
                    limiti: "01",
                    annocs: "0000",
                    stgene: "01",
                    stspor: "00",
                    stcope: "00",
                    sttamp: "00",
                    stches: "00",
                    stpart: "00",
                    stfini: "00",
                    stimpi: "00",
                    stnote: "00",
                    stoccu: "01",
                    sogocc: "Fattoria Agricola",
                    natocc: "02",
                    tipocc: "02",
                    vincol: "01",
                    intcul: "00",
                    autali: "00",
                    dsturb: "03",
                    iterur: "00",
                    titori: "NO",
                    ante67: "SI",
                    ante42: "SI",
                    corcat: "NO",
                    ceragi: "00",
                    collst: "00",
                    docamb: "01",
                    vulssm: "00",
                    vulamb: "01",
                    stimav: "1500000",
                    stimnt: "Valutazione terreni agricoli",
                    annovl: "2024",
                    canloc: "50000",
                    prgprc: "00",
                    delibe: "00",
                    espgar: "00",
                    esitoa: "00"
                }
            ];
            var oModel = new JSONModel(aScheme);
            oModel.setDefaultBindingMode("TwoWay");
            return oModel;
        },
        createOAModel: function () {
            var aOA = [
                {
                    idscheda: "00000001",
                    idpos: "00001",
                    statopos: "A",
                    ernam: "USER001",
                    erdat: "20260901",
                    erzet: "120000",
                    aenam: "",
                    aedat: "",
                    aezet: "",
                    intreno_oa: "INT001",
                    aoid: "OA00001",
                    objnr_oa: "OBJOA001",
                    objnrtrg_oa: "OBJUL001",
                    intreno_ul: "INTU001",
                    bukrs: "1000",
                    swenr: "0000000100",
                    sgrnr: "0000000200",
                    sgenr: "0000000300",
                    smenr: "0000000400",
                    zztpca: "01",
                    zztped: "01",
                    zzbelf: "MI001",
                    zzfogl: "45",
                    zzsezu: "A",
                    zzpart: "123",
                    zzsub: "1",
                    zzdeno: "00",
                    zztppt: "01",
                    zzccom: "Z100"
                },
                {
                    idscheda: "00000001",
                    idpos: "00002",
                    statopos: "A",
                    ernam: "USER001",
                    erdat: "20260901",
                    erzet: "120500",
                    aenam: "",
                    aedat: "",
                    aezet: "",
                    intreno_oa: "INT002",
                    aoid: "OA00002",
                    objnr_oa: "OBJOA002",
                    objnrtrg_oa: "OBJUL002",
                    intreno_ul: "INTU002",
                    bukrs: "1000",
                    swenr: "0000000100",
                    sgrnr: "0000000200",
                    sgenr: "0000000301",
                    smenr: "0000000401",
                    zztpca: "01",
                    zztped: "02",
                    zzbelf: "MI001",
                    zzfogl: "45",
                    zzsezu: "A",
                    zzpart: "124",
                    zzsub: "2",
                    zzdeno: "00",
                    zztppt: "01",
                    zzccom: "Z100"
                },
                {
                    idscheda: "00000002",
                    idpos: "00001",
                    statopos: "A",
                    ernam: "USER002",
                    erdat: "20260815",
                    erzet: "140000",
                    aenam: "USER001",
                    aedat: "20260901",
                    aezet: "150000",
                    intreno_oa: "INT003",
                    aoid: "OA00003",
                    objnr_oa: "OBJOA003",
                    objnrtrg_oa: "OBJUL003",
                    intreno_ul: "INTU003",
                    bukrs: "1000",
                    swenr: "0000000101",
                    sgrnr: "0000000201",
                    sgenr: "0000000302",
                    smenr: "0000000402",
                    zztpca: "01",
                    zztped: "01",
                    zzbelf: "MI002",
                    zzfogl: "46",
                    zzsezu: "B",
                    zzpart: "200",
                    zzsub: "0",
                    zzdeno: "00",
                    zztppt: "01",
                    zzccom: "Z100"
                }
            ];
            var oModel = new JSONModel(aOA);
            oModel.setDefaultBindingMode("TwoWay");
            return oModel;
        }
    };
});